<script setup>
import { reactive, ref } from "vue";
import { useRouter } from "vue-router";
import { api } from "../api/client";
const router = useRouter(); const submitting = ref(false);
const form = reactive({ first_name: "", last_name: "", phone_number: "", password: "" });
const error = ref("");
async function submit() { submitting.value = true; error.value = ""; try { const result = await api.post("/parents", form); localStorage.setItem("jwt", result.jwt || ""); localStorage.setItem("parent", String(result.parent?.id || "")); localStorage.setItem("parent_data", JSON.stringify(result.parent || result)); router.push("/parent_dashboard"); } catch (cause) { error.value = cause.message || "注册失败"; } finally { submitting.value = false; } }
</script>
<template><div class="login-shell light-login"><section class="login-card" style="max-width:800px"><aside class="login-aside"><RouterLink class="brand-lockup" to="/"><img class="brand-mark" src="/assets/brand/para-kindergarten-logo.png" alt="ParaKindergarten" /><span><strong class="brand-name">ParaKindergarten</strong><small class="brand-subtitle">FAMILY CONNECTION</small></span></RouterLink><h1>一起陪孩子长大。</h1><p>创建家长账号，关联孩子后即可查看成长、考勤和聊天记录。</p></aside><div class="login-form-panel"><span class="mono-label">NEW FAMILY PROFILE</span><h2 style="margin-top:16px">创建家长账号</h2><p>填写基础信息，完成后即可进入家庭陪伴空间。</p><div v-if="error" class="notice error" style="margin-bottom:14px">{{ error }}</div><form class="login-form" @submit.prevent="submit"><div class="form-grid"><div class="field"><label>名字</label><input v-model="form.first_name" required placeholder="请输入名字" /></div><div class="field"><label>姓氏</label><input v-model="form.last_name" required placeholder="请输入姓氏" /></div><div class="field"><label>电话号码</label><input v-model="form.phone_number" required placeholder="请输入电话号码" /></div><div class="field"><label>密码</label><input v-model="form.password" required type="password" placeholder="设置登录密码" /></div></div><button class="button button-primary" type="submit" :disabled="submitting">{{ submitting ? '创建中...' : '创建账号' }}</button></form><div class="login-links"><RouterLink to="/parent_login">已有账号？返回登录</RouterLink><RouterLink to="/">返回首页</RouterLink></div></div></section></div></template>
