<script setup>
import { onMounted, ref, watch } from "vue";
import { LoaderCircle, MessageCircle, RefreshCw } from "lucide-vue-next";
import { api } from "../api/client";
const students = ref([]); const selectedStudentId = ref(""); const sessions = ref([]); const selectedSession = ref(null); const message = ref(""); const loading = ref(true);
function name(student) { return [student?.first_name, student?.second_name, student?.surname].filter(Boolean).join(" "); }
async function loadSessions() { if (!selectedStudentId.value) return; try { const data = await api.get(`/parent/children/${selectedStudentId.value}/chat_sessions`, "parent"); sessions.value = Array.isArray(data) ? data : []; selectedSession.value = sessions.value[0] || null; } catch (cause) { message.value = cause.message || "聊天记录加载失败"; } }
onMounted(async () => { try { const data = await api.get("/parent/children", "parent"); students.value = Array.isArray(data) ? data : []; selectedStudentId.value = students.value[0]?.id ? String(students.value[0].id) : ""; await loadSessions(); } catch (cause) { message.value = cause.message || "聊天记录加载失败"; } finally { loading.value = false; } }); watch(selectedStudentId, loadSessions);
</script>
<template><div><div class="page-heading"><div><span class="mono-label">FAMILY / AI COMPANION</span><h1>儿童聊天记录</h1><p>查看已绑定孩子在儿童端的 AI 陪伴对话。</p></div><button class="button button-light" @click="loadSessions"><RefreshCw :size="15" />刷新</button></div><div v-if="message" class="notice error" style="margin-bottom:14px">{{ message }}</div><section class="surface surface-pad"><div class="field" style="max-width:380px"><label for="parent-chat-child">选择孩子</label><select id="parent-chat-child" v-model="selectedStudentId"><option v-for="student in students" :key="student.id" :value="String(student.id)">{{ name(student) }}</option></select></div></section><div class="data-grid" style="grid-template-columns:280px minmax(0,1fr); margin-top:18px"><section class="surface surface-pad"><div class="surface-title"><h2>对话列表</h2><span>{{ sessions.length }} SESSIONS</span></div><div v-if="loading" class="empty-state"><LoaderCircle class="spin" :size="24" /></div><div v-else-if="!sessions.length" class="empty-state"><MessageCircle :size="26" style="margin-bottom:8px; color:#75cfc3" /><strong>暂无聊天记录</strong><span>孩子开始一次对话后会显示在这里。</span></div><div v-else style="display:grid; gap:7px"><button v-for="session in sessions" :key="session.id" class="button button-light" :class="{ 'button-primary': selectedSession?.id === session.id }" style="justify-content:flex-start; text-align:left" @click="selectedSession = session">{{ session.title || '儿童陪伴对话' }}</button></div></section><section class="surface surface-pad"><div class="surface-title"><h2>对话内容</h2><span>{{ selectedSession?.messages?.length || 0 }} MESSAGES</span></div><div v-if="!selectedSession" class="empty-state">请选择左侧对话</div><div v-else style="display:grid; gap:10px"><article v-for="item in selectedSession.messages || []" :key="item.id" class="chat-bubble" :class="{ user: item.role === 'user' }"><small style="display:block; margin-bottom:5px; opacity:.65">{{ item.role === 'user' ? '孩子' : 'AI 陪伴老师' }} · {{ item.created_at ? new Date(item.created_at).toLocaleString('zh-CN') : '' }}</small>{{ item.content }}</article></div></section></div></div></template>
<style scoped>.spin { animation: spin 1s linear infinite; } @keyframes spin { to { transform:rotate(360deg); } }</style>
